/* ============================================================
   NAV — Auth-aware admin link + GitHub publish
   ============================================================ */

(function () {
  const SESSION_KEY = 'portfolio_auth';
  const isLoggedIn = sessionStorage.getItem(SESSION_KEY) === 'true';
  const adminLink = document.getElementById('nav-admin-link');
  if (!adminLink) return;

  if (!isLoggedIn) return;

  // Swap link to greeting
  adminLink.textContent = 'Hello Nile';
  adminLink.href = '#';

  // Build dropdown wrapper
  const wrapper = document.createElement('div');
  wrapper.style.cssText = 'position:relative; display:inline-flex;';

  const dropdown = document.createElement('div');
  dropdown.id = 'nav-dropdown';
  dropdown.style.cssText = [
    'display:none',
    'position:absolute',
    'top:24px',
    'right:0',
    'background:#FFFFFF',
    'border:1px solid #000000',
    'z-index:999',
    'min-width:160px',
  ].join(';');

  // ── Publish button ──────────────────────────────────────
  const publishBtn = document.createElement('button');
  publishBtn.textContent = 'Publish';
  publishBtn.className = 'btn--secondary';
  publishBtn.style.cssText = 'width:100%; justify-content:flex-start; white-space:nowrap;';
  publishBtn.addEventListener('click', () => doPublish(publishBtn));
  dropdown.appendChild(publishBtn);

  // ── GitHub Settings button ───────────────────────────────
  const ghBtn = document.createElement('button');
  ghBtn.textContent = 'GitHub Settings';
  ghBtn.className = 'btn--secondary';
  ghBtn.style.cssText = 'width:100%; justify-content:flex-start; white-space:nowrap;';
  ghBtn.addEventListener('click', () => { dropdown.style.display = 'none'; openGHSettings(); });
  dropdown.appendChild(ghBtn);

  // ── Log out button ───────────────────────────────────────
  const logoutBtn = document.createElement('button');
  logoutBtn.textContent = 'Log out';
  logoutBtn.className = 'btn--secondary';
  logoutBtn.style.cssText = 'width:100%; justify-content:flex-start; white-space:nowrap;';
  logoutBtn.addEventListener('click', () => {
    sessionStorage.removeItem(SESSION_KEY);
    window.location.href = 'login.html';
  });
  dropdown.appendChild(logoutBtn);

  adminLink.parentNode.insertBefore(wrapper, adminLink);
  wrapper.appendChild(adminLink);
  wrapper.appendChild(dropdown);

  // Toggle dropdown on click
  adminLink.addEventListener('click', (e) => {
    e.preventDefault();
    const isOpen = dropdown.style.display === 'block';
    dropdown.style.display = isOpen ? 'none' : 'block';
  });

  // Close on outside click
  document.addEventListener('click', (e) => {
    if (!wrapper.contains(e.target)) {
      dropdown.style.display = 'none';
    }
  });

  // ── GitHub API publish ───────────────────────────────────
  async function doPublish(btn) {
    const token  = localStorage.getItem('__gh_token__');
    const repo   = localStorage.getItem('__gh_repo__');    // "username/repo"
    const branch = localStorage.getItem('__gh_branch__') || 'main';

    if (!token || !repo) {
      dropdown.style.display = 'none';
      openGHSettings('Enter your GitHub details to enable publishing.');
      return;
    }

    btn.textContent = 'Publishing…';
    btn.disabled = true;
    dropdown.style.display = 'none';

    try {
      // Gather all admin-editable localStorage keys
      const PREFIXES = ['cb_', 'title_', 'date_', 'dither_', 'pattern_', 'bg_', 'page_hidden_'];
      const data = {};
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key === 'home_para' || PREFIXES.some(p => key.startsWith(p))) {
          data[key] = localStorage.getItem(key);
        }
      }

      // Build the new published-data.js content
      const version = String(Date.now());
      const lines = [
        '/* Auto-generated by Publish — do not edit manually */',
        '(function () {',
        '  var DATA = ' + JSON.stringify(data) + ';',
        "  var VERSION = '" + version + "';",
        "  var PREFIXES = ['cb_', 'title_', 'date_', 'dither_', 'pattern_', 'bg_', 'page_hidden_'];",
        "  if (localStorage.getItem('__pub_v__') !== VERSION) {",
        '    Object.keys(localStorage).forEach(function (k) {',
        "      if (k === 'home_para' || PREFIXES.some(function (p) { return k.indexOf(p) === 0; })) {",
        '        localStorage.removeItem(k);',
        '      }',
        '    });',
        "    Object.keys(DATA).forEach(function (k) { localStorage.setItem(k, DATA[k]); });",
        "    localStorage.setItem('__pub_v__', VERSION);",
        '  }',
        '})();',
        '',
      ];
      const fileContent = lines.join('\n');

      // Base64-encode (handles Unicode via URI encoding)
      const encoded = btoa(unescape(encodeURIComponent(fileContent)));

      const apiBase = 'https://api.github.com/repos/' + repo + '/contents/js/published-data.js';
      const headers = {
        'Authorization': 'token ' + token,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      };

      // Get current file SHA (required for updates)
      let sha;
      const getRes = await fetch(apiBase + '?ref=' + encodeURIComponent(branch), { headers });
      if (getRes.ok) {
        sha = (await getRes.json()).sha;
      } else if (getRes.status !== 404) {
        const err = await getRes.json().catch(() => ({}));
        throw new Error('GitHub error ' + getRes.status + (err.message ? ': ' + err.message : ''));
      }

      // Push updated file
      const body = {
        message: 'Publish: update portfolio content',
        content: encoded,
        branch: branch,
      };
      if (sha) body.sha = sha;

      const putRes = await fetch(apiBase, { method: 'PUT', headers, body: JSON.stringify(body) });
      if (!putRes.ok) {
        const err = await putRes.json().catch(() => ({}));
        throw new Error('GitHub error ' + putRes.status + (err.message ? ': ' + err.message : ''));
      }

      btn.textContent = 'Published!';
      setTimeout(() => { btn.textContent = 'Publish'; btn.disabled = false; }, 3000);

    } catch (err) {
      console.error('Publish failed:', err);
      btn.textContent = 'Error — try again';
      btn.disabled = false;
    }
  }

  // ── GitHub Settings modal ────────────────────────────────
  function openGHSettings(notice) {
    const overlay = document.createElement('div');
    overlay.style.cssText = [
      'position:fixed', 'inset:0', 'background:rgba(0,0,0,0.6)',
      'display:flex', 'align-items:center', 'justify-content:center', 'z-index:10000',
    ].join(';');

    const modal = document.createElement('div');
    modal.style.cssText = [
      'background:#fff', 'border:1px solid #000', 'padding:24px',
      'width:380px', 'max-width:92vw',
      'display:flex', 'flex-direction:column', 'gap:12px',
      'font-family:inherit',
    ].join(';');

    const noticeHtml = notice
      ? '<p style="margin:0;font-size:13px;color:#9A1638;">' + esc(notice) + '</p>'
      : '';

    modal.innerHTML =
      '<h2 style="margin:0;font-size:16px;">GitHub Settings</h2>' +
      noticeHtml +
      '<p style="margin:0;font-size:12px;color:#555;">Publish commits <code>js/published-data.js</code> to your repo. GitHub Pages auto-deploys on each commit.</p>' +
      mkField('Personal Access Token', 'gh-token', 'password', 'ghp_…', localStorage.getItem('__gh_token__') || '') +
      mkField('Repository', 'gh-repo', 'text', 'username/repo', localStorage.getItem('__gh_repo__') || '') +
      mkField('Branch', 'gh-branch', 'text', 'main', localStorage.getItem('__gh_branch__') || 'main') +
      '<hr style="border:none;border-top:1px solid #E5E5E5;margin:4px 0;">' +
      '<p style="margin:0;font-size:12px;color:#555;">Connect a public Google Drive folder so images appear in the picker automatically.</p>' +
      mkField('Drive Folder ID', 'drive-folder', 'text', 'Paste folder ID from Drive URL…', localStorage.getItem('__drive_folder__') || '') +
      mkField('Drive API Key', 'drive-key', 'password', 'AIza…', localStorage.getItem('__drive_key__') || '') +
      '<div style="display:flex;gap:8px;justify-content:flex-end;margin-top:4px;">' +
        '<button id="gh-cancel" class="btn--secondary">Cancel</button>' +
        '<button id="gh-save" class="btn--secondary">Save</button>' +
      '</div>';

    overlay.appendChild(modal);
    document.body.appendChild(overlay);

    modal.querySelector('#gh-cancel').addEventListener('click', () => overlay.remove());
    modal.querySelector('#gh-save').addEventListener('click', () => {
      const t  = modal.querySelector('#gh-token').value.trim();
      const r  = modal.querySelector('#gh-repo').value.trim();
      const b  = modal.querySelector('#gh-branch').value.trim() || 'main';
      const df = modal.querySelector('#drive-folder').value.trim();
      const dk = modal.querySelector('#drive-key').value.trim();
      if (t)  localStorage.setItem('__gh_token__', t);
      if (r)  localStorage.setItem('__gh_repo__', r);
      localStorage.setItem('__gh_branch__', b);
      if (df) localStorage.setItem('__drive_folder__', df);
      if (dk) localStorage.setItem('__drive_key__', dk);
      overlay.remove();
    });
  }

  function mkField(labelText, id, type, placeholder, value) {
    return '<div style="display:flex;flex-direction:column;gap:4px;">' +
      '<label for="' + id + '" style="font-size:12px;">' + labelText + '</label>' +
      '<input id="' + id + '" type="' + type + '" placeholder="' + placeholder + '" value="' + esc(value) + '" ' +
        'style="padding:6px 8px;border:1px solid #000;font-family:inherit;font-size:13px;box-sizing:border-box;width:100%;">' +
      '</div>';
  }

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
  }
})();
