/* Auto-generated by Publish — do not edit manually */
(function () {
  var DATA = {"title_graphic-project-03":"Puppet Rigs","dither_portfolio":"#A09280","title_motion-project-01":"Product Institute Reel","bg_portfolio":"#E7E1D4","pattern_portfolio":"sparse","dither_graphic-project-03":"#A09280","bg_motion-project-01":"#D5DCE8","title_portfolio":"Portfolio","cb_graphic-project-03":"[{\"id\":\"skfrfri\",\"type\":\"image\",\"images\":[{\"src\":\"images/page%20builder%20images/Info%20people.png\",\"alt\":\"\",\"scale\":100}],\"fill\":\"#FFFFFF\"}]","home_para":"This website serves me as a growing archive of projects and daydreams bigger than life itself. My goal is to document my projects as they unfold, miss spellings included. I've made a living as an artist since 2020, but it has been my life since 1998. Below is a curated index of my work so far. However you ended up on this page, thanks for taking a look around.","cb_motion-project-01":"[{\"id\":\"xm5ur3q\",\"type\":\"text\",\"content\":\"<div class=\\\"heading-md\\\">Animated UI Reel</div><div class=\\\"label\\\">Mar 13 2025</div>\",\"fill\":\"#FFFFFF\"},{\"id\":\"2ud04lq\",\"type\":\"video\",\"url\":\"<iframe width=\\\"560\\\" height=\\\"315\\\" src=\\\"https://www.youtube.com/embed/5kT6L2R7eW8?si=XQcy9ISIBKfFFrz-\\\" title=\\\"YouTube video player\\\" frameborder=\\\"0\\\" allow=\\\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\\\" referrerpolicy=\\\"strict-origin-when-cross-origin\\\" allowfullscreen></iframe>\",\"fill\":\"#404040\",\"hugTop\":true},{\"id\":\"50wawvh\",\"type\":\"text\",\"content\":\"<div class=\\\"body-base\\\">No description for this video yet...</div>\",\"fill\":\"#FFFFFF\",\"hugTop\":true}]","bg_graphic-project-03":"#E7E1D4","pattern_motion-project-01":"checker","dither_motion-project-01":"#CBD5E0"};
  var VERSION = '1776199658939';
  var PREFIXES = ['cb_', 'title_', 'date_', 'dither_', 'pattern_', 'bg_', 'page_hidden_'];
  if (localStorage.getItem('__pub_v__') !== VERSION) {
    Object.keys(localStorage).forEach(function (k) {
      if (k === 'home_para' || PREFIXES.some(function (p) { return k.indexOf(p) === 0; })) {
        localStorage.removeItem(k);
      }
    });
    Object.keys(DATA).forEach(function (k) { localStorage.setItem(k, DATA[k]); });
    localStorage.setItem('__pub_v__', VERSION);
  }
})();
