/* Auto-generated by Publish — do not edit manually */
(function () {
  var DATA = {"home_para":"This website serves me as a growing archive of projects and daydreams bigger than life itself. My goal is to document my projects as they unfold, miss spellings included. I've made a living as an artist since 2020, but it has been my life since 1998. Below is a curated index of my work so far. However you ended up on this page, thanks for taking a look around."};
  var VERSION = '1776094431380';
  var PREFIXES = ['cb_', 'title_', 'date_', 'dither_', 'pattern_', 'bg_', 'page_hidden_'];
  if (localStorage.getItem('__pub_v__') !== VERSION) {
    Object.keys(localStorage).forEach(function (k) {
      if (k === 'home_para' || PREFIXES.some(function (p) { return k.indexOf(p) === 0; })) {
        localStorage.removeItem(k);
      }
    });
    Object.keys(DATA).forEach(function (k) { localStorage.setItem(k, DATA[k]); });
    localStorage.setItem('__pub_v__', VERSION);
  }
})();
